remote_theme: "mmistakes/minimal-mistakes@4.21.0"
minimal_mistakes_skin: "mint" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
title: familie-sucht-haus.eu
email: admin@familie-sucht-haus.eu
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://familie-sucht-haus.eu" # the base hostname & protocol for your site, e.g. http://example.com

locale: "de-DE"

# Build settings

plugins:
  - jekyll-feed
  - jekyll-include-cache

# Site Author
author:
  name             : "Daniela & Björn Woppmann"
  avatar           : "/assets/images/beide.jpg"
  bio              : "suchen ein Haus in Mannheim. Sie haben einen Hinweis? Bitte kontaktieren Sie uns:"
  location         : "Telefon:&nbsp;<a href=tel:06214834382>0621/4834382</a>"
  email            : "hinweis@familie-sucht-haus.eu"

include:
  - robots.txt

exclude:
  - Gemfile
  - LICENSE